const langCodes = {
    aa: "Afarca",
    ab: "Abhazca",
    ae: "Avestaca",
    af: "Afrikaanca",
    ak: "Akanca",
    am: "Amharca",
    an: "Aragonca",
    ar: "Arapça",
    as: "Assamca",
    av: "Avarca",
    ay: "Aymaraca",
    az: "Azerice",
    ba: "Başkırtça",
    be: "Beyaz Rusça",
    ru: "Rusça",
    uk: "Ukraynaca",
    tr: "Türkçe",
    el: "Yunanca",
    bg: "Bulgarca",
    bh: "Biharca",
    bi: "Bislama",
    bm: "Bambaraca",
    bn: "Bengalce",
    bo: "Tibetçe",
    br: "Bretonca",
    bs: "Boşnakça",
    ca: "Katalanca",
    ce: "Çeçence",
    ch: "Chamorro",
    co: "Korsikaca",
    cr: "Cree",
    cs: "Çekçe",
    cu: "Kilise Slavcası",
    cv: "Çuvaşça",
    cy: "Galce",
    da: "Danca",
    de: "Almanca",
    dv: "Divehi",
    dz: "Dzongkha",
    ee: "Ewe",
    el: "Yunanca",
    en: "İngilizce",
    eo: "Esperanto",
    es: "İspanyolca",
    et: "Estonca",
    eu: "Baskça",
    fa: "Farsça",
    ff: "Fula",
    fi: "Fince",
    fj: "Fiji dili",
    fo: "Faroe dili",
    fr: "Fransızca",
    fy: "Frizce",
    ga: "İrlandaca",
    gd: "İskoçça",
    gl: "Gallego",
    gn: "Guaraní",
    gu: "Gujarati",
    gv: "Man dili",
    ha: "Hausa",
    he: "İbranice",
    hi: "Hintçe",
    ho: "Hiri Motu",
    hr: "Hırvatça",
    ht: "Haitili kreol dili",
    hu: "Macarca",
    hy: "Ermenice",
    hz: "Herero",
    ia: "Interlingua",
    id: "Endonezyaca",
    ie: "Interlingue",
    ig: "İbo dili",
    ii: "Sichuan Yi",
    ik: "Inupiak",
    io: "Ido",
    is: "İzlandaca",
    it: "İtalyanca",
    iu: "İnuktitut",
    ja: "Japonca",
    jv: "Cava dili",
    ka: "Gürcüce",
    kg: "Kongo dili",
    ki: "Kikuyu",
    kj: "Kuanyama",
    kk: "Kazakça",
    kl: "Grönland dili",
    km: "Khmer",
    kn: "Kannada",
    ko: "Korece",
    kr: "Kanuri",
    ks: "Keşmirce",
    ku: "Kürtçe",
    kv: "Komi",
    kw: "Korn dili",
    ky: "Kırgızca",
    la: "Latince",
    lb: "Lüksemburgca",
    lg: "Ganda",
    li: "Limburgca",
    ln: "Lingala",
    lo: "Lao dili",
    lt: "Litvanca",
    lu: "Luba-Katanga",
    lv: "Let",
    pl: "Lehçe",
    pt: "Portekizce",
    no: "Norveççe",
    mn: "Moğolca",
    ne: "Nepalce",
    pa: "Pencapça",
    si: "Sinhalese",
    ta: "Tamilce",
    te: "Teluguca",
    ur: "Urduca",
    uz: "Özbekçe",
    vi: "Vietnamca",
    zh: "Çince",
  };
  export default langCodes;